# Generated by Django 5.2.8 on 2025-11-10 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter phone as digits, optional leading +, length 7-15.', regex='^\\+?\\d{7,15}$')])),
                ('address', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
